### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by pzwaag** [lucaskoensgen/pcs_scraper#3]
This is a very nice Python package to get information from www.procyclingstats.com.
However, when trying to get a list of all riders from the teams "totalenergies" and "q36.5-pro-cycling-team", the result is a strange errorcode: 

`File [c:\Programs\Anaconda\envs\HW_5\lib\site-packages\pcs_scraper\team.py:42](file:///C:/Programs/Anaconda/envs/HW_5/lib/site-packages/pcs_scraper/team.py:42), in Team.get_riders(self)
     [40](file:///c%3A/Programs/Anaconda/envs/HW_5/lib/site-packages/pcs_scraper/team.py?line=39) soup = self.soup
     [41](file:///c%3A/Programs/Anaconda/envs/HW_5/lib/site-packages/pcs_scraper/team.py?line=40) # table including all riders for year
---> [42](file:///c%3A/Programs/Anaconda/envs/HW_5/lib/site-packages/pcs_scraper/team.py?line=41) riders_table = soup.find("div", class_ = "ttabs tabb").find("ul", class_ = "list pad2").find_all("li")
     [44](file:///c%3A/Programs/Anaconda/envs/HW_5/lib/site-packages/pcs_scraper/team.py?line=43) # preset empty list for riders
     [45](file:///c%3A/Programs/Anaconda/envs/HW_5/lib/site-packages/pcs_scraper/team.py?line=44) riders = []

AttributeError: 'NoneType' object has no attribute 'find'`

What could possibly be the reason of this error? 
No problems with all World Tour Teams.

Kind regards,
Pim.

**Comment by pzwaag** [comment]
Found another solution (using FME)

**Comment by lucaskoensgen** [comment]
In regards to Q36.5, for some reason PCS decided to not include the team's year in the href for 2023 – I think this is an error on their part due to the rest of their very consistent formatting. It is simply https://www.procyclingstats.com/team/q365-pro-cycing-team, when it is expected to be https://www.procyclingstats.com/team/q365-pro-cycing-team-2023 or https://www.procyclingstats.com/team/q365-pro-cycing-2023. 

For example the following year works as per expected:

q365 = pcs.Team("q365-pro-cycing", 2024)
q365_riders = q365.get_riders()

At the moment, if you really need a workaround for Q36.5 try this, it will add "-team" instead of the year:

q365 = pcs.Team("q365-pro-cycing", "team")
q365_riders = q365.get_riders()

I was not able to replicate this error for totalenergies. Please note that for totalenergies, the team name according to PCS is "team-totalenergies". So you would search for the team object and riders like this:

totalenergies = pcs.Team("team-totalenergies", 2023)
totalenergies_riders = totalenergies.get_riders()

Furthermore, the names of the team can be found for a given year by using:

team_options_2023 = pcs.teams_by_year(year = 2023, gender = 'M')
